// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DisplayNotifications
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidDisplayNotificationsPackageString = "131ca5cd-ca59-45ba-b97d-db4be15fe841";
        public static Guid guidDisplayNotificationsPackage = new Guid(guidDisplayNotificationsPackageString);

        public const string guidDisplayNotificationsPackageCmdSetString = "9ffca492-ec05-4786-8e91-b2972eb5db44";
        public static Guid guidDisplayNotificationsPackageCmdSet = new Guid(guidDisplayNotificationsPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int NotificationToolWindowCommandId = 0x0100;
    }
}