// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace JsonToCSharpCodeGeneration
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidJsonToCSharpCodeGenerationPackageString = "4fe18284-0dbd-4936-9f6e-3ff7304dc7c2";
        public static Guid guidJsonToCSharpCodeGenerationPackage = new Guid(guidJsonToCSharpCodeGenerationPackageString);

        public const string guidVisibilityContextString = "878bc455-61ba-459b-b18d-6922cde6ce19";
        public static Guid guidVisibilityContext = new Guid(guidVisibilityContextString);

        public const string guidJsonToCSharpCodeGenerationPackageCmdSetString = "78327699-c6b2-4daf-a7d1-2877b33b9288";
        public static Guid guidJsonToCSharpCodeGenerationPackageCmdSet = new Guid(guidJsonToCSharpCodeGenerationPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ApplyCodeGenerationCommandId = 0x0100;
    }
}