// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExternalSearch
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidExternalSearchPackageString = "2f33e5a2-ff60-4424-b309-e57787c5d3fa";
        public static Guid guidExternalSearchPackage = new Guid(guidExternalSearchPackageString);

        public const string guidExternalSearchPackageCmdSetString = "20580f36-35da-4d5f-95d6-d2d2d4df35fd";
        public static Guid guidExternalSearchPackageCmdSet = new Guid(guidExternalSearchPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int SearchCommandId = 0x0100;
    }
}