// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ToolsMenuCommand
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidToolsMenuCommandPackageString = "c4cf0872-23e7-4230-b219-5aaf03be855c";
        public static Guid guidToolsMenuCommandPackage = new Guid(guidToolsMenuCommandPackageString);

        public const string guidToolsMenuCommandPackageCmdSetString = "ec82d9e6-e11d-4efc-90be-5cf7b845e00d";
        public static Guid guidToolsMenuCommandPackageCmdSet = new Guid(guidToolsMenuCommandPackageCmdSetString);

        public const string guidImagesString = "14d2eab7-1627-4caa-a2f9-00711401a08f";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int MyCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}