// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PropertiesToolWindow
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPropertiesToolWindowPackageString = "8e6f82bf-a6d4-45a1-9f3a-3491d95dd601";
        public static Guid guidPropertiesToolWindowPackage = new Guid(guidPropertiesToolWindowPackageString);

        public const string guidPropertiesToolWindowPackageCmdSetString = "7f78ef71-513e-4a58-a062-67c961d628f5";
        public static Guid guidPropertiesToolWindowPackageCmdSet = new Guid(guidPropertiesToolWindowPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolWindowCommandId = 0x0100;
    }
}